objects/Twitter_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Pic__c</fullName>
        <formula>IMAGE( Profile__c ,  Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profile Pic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Twitter_Handle__c</fullName>
        <externalId>true</externalId>
        <label>Twitter Handle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>followers_count__c</fullName>
        <label>followers_count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Twitter Follower</label>
    <nameField>
        <label>Followers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitter Follower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TwitterFollowersMap.cls
public with sharing class TwitterFollowersMap {
    @AuraEnabled(cacheable = true)
    public static List<Twitter_Follower__c> getFollowers() {
        List<Twitter_Follower__c> followers = [ SELECT Id, 
                                               Name, Twitter_Handle__c, 
                                               Location__c, Description__c, followers_count__c, 
                                               Profile__c, Profile_Pic__c FROM Twitter_Follower__c
                                               Where Location__c != null
                                              Limit 100
                                              ];
        return followers;
    }
    
    @AuraEnabled(cacheable = true ) 
    public static List<Twitter_Follower__c> findFollowers(String searchParam, String locationParam) {
        String likeFilter = '\'%'+searchParam+'%\'';
        String locationFilter = '\'%'+locationParam+'%\'';
        String Query = 'SELECT Id, Name, Twitter_Handle__c, Location__c, Description__c, followers_count__c,'+
                       +'Profile__c, Profile_Pic__c FROM Twitter_Follower__c Where Name != null ';
        if ( searchParam != null ) {
            Query += ' AND Name Like ' + likeFilter ;
        }
        if ( locationParam != null ) {
            Query += ' AND Location__c Like ' + locationFilter ;
        }
        Query += ' Order By LastModifiedDate ASC Limit 100';
        List<sObject> objectList = new List<sObject>();   
        objectList = Database.Query(Query);
        return objectList;
    }
}