objects/Twitter_Endpoints__mdt.object
<CustomObject>
    <fields>
        <fullName>Timeline__c</fullName>
        <label>Timeline</label>
        <type>Url</type>
    </fields>
    <label>Twitter Endpoint</label>
    <pluralLabel>Twitter Endpoint</pluralLabel>
</CustomObject>

objects/Twitter_Follower__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Following__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Following?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Twitter_Handle__c</fullName>
        <externalId>true</externalId>
        <label>Twitter Handle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Twitter_Id__c</fullName>
        <label>Twitter Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>followers_count__c</fullName>
        <label>followers_count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Twitter Follower</label>
    <nameField>
        <label>Followers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitter Follower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Twitter_Infos__mdt.object
<CustomObject>
    <description>Twitter Info MD will be used to store all the EndPoint and all the Sensitive Information which will be useful to Integrate Salesforce with Twitter.</description>
    <fields>
        <fullName>api_endpoint__c</fullName>
        <label>api endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>oauth_consumer_Secret__c</fullName>
        <label>oauth consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oauth_consumer_key__c</fullName>
        <label>oauth_consumer_key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oauth_token__c</fullName>
        <label>oauth_token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>oauth_token_secret__c</fullName>
        <label>oauth_token_secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Twitter Info</label>
    <pluralLabel>Twitter Infos</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Twitter_User_Name__c</fullName>
        <label>Twitter User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/TwitterOperations.cls
/*
 * @Author : Amit Singh
 * @Date : 7th Oct 2019
 * @Description : A Playground class for Twitter
 * @Name : TwitterOperations
*/
public with sharing class TwitterOperations {
    
    public static String getTwitterFollowers(String cursor){
        List<User> userIn = [Select Id, Name, Twitter_User_Name__c From User Where Id =: UserInfo.getUserId() ];
        if(userIn != null && userIn.size() > 0){
            List<Twitter_Infos__mdt> tokenSecretInfo = TwitterController.twitterSecretTokenInfo(userIn[0].Twitter_User_Name__c);
            List<Twitter_Endpoints__mdt> endpoints = oAuth1OUtility.getEndpoints();
            String screen_name = userIn.get(0).Twitter_User_Name__c;
            if ( endpoints == null) {
                return null;
            }
            String endPoint = '';
            if( cursor == null) {
                endPoint = '/1.1/followers/list.json?cursor=-1&count=200&screen_name='+screen_name+'&skip_status=true&include_user_entities=false';
            } else {
                endPoint = '/1.1/followers/list.json?cursor='+cursor+'&count=200&screen_name='+screen_name+'&skip_status=true&include_user_entities=false';
            }
            if(tokenSecretInfo != null && tokenSecretInfo.size() > 0){
                HttpRequest httpReq = oAuth1OUtility.prepareRequest(tokenSecretInfo[0].api_endpoint__c,
                                                                    tokenSecretInfo[0].oauth_consumer_key__c,
                                                                    tokenSecretInfo[0].oauth_consumer_Secret__c,
                                                                    tokenSecretInfo[0].oauth_token__c,
                                                                    tokenSecretInfo[0].oauth_token_secret__c,
                                                                    endPoint, 
                                                                    'GET');
                
                HttpResponse httpRes = new HttpResponse();
                try{
                    httpRes = (new Http()).send(httpReq);
                    if(httpRes.getStatusCode() == 200){
                        String response = httpRes.getBody();
                        TwitterFollowerWrapper wrapper = (TwitterFollowerWrapper)JSON.deserialize(response, TwitterFollowerWrapper.class);
                        List<TwitterFollowerWrapper.cls_users> userList = wrapper.users;
                        String next_cursor = wrapper.next_cursor_str;
                        List< Twitter_Follower__c > followers = new List< Twitter_Follower__c >();
                        for( TwitterFollowerWrapper.cls_users user : userList ) {
                            Twitter_Follower__c f = new Twitter_Follower__c ();
                            f.Name = user.name;
                            f.Twitter_Handle__c  = user.screen_name;
                            f.Location__c  = user.location;
                            f.Description__c  = user.description;
                            f.followers_count__c = user.followers_count;
                            f.Profile__c  = user.profile_image_url_https;
                            f.Following__c = true;
                            f.Twitter_Id__c = user.id_str;
                            followers.add(f); 
                        }
                        upsert followers Twitter_Handle__c;
                        
                        return next_cursor;
                    }else{
                        String response = httpRes.getBody();
                        System.debug(' Error Response ' + response);
                        return null;
                    }
                }catch(Exception ex){
                    System.debug(' #### Exception Executed '+ex.getStackTraceString());
                    System.debug(' #### Exception Executed '+ex.getCause());
                    System.debug(' #### Exception Executed '+ex.getLineNumber());
                    System.debug(' #### Exception Executed '+ex.getMessage());
                    return null;
                }
            }
        }
        return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static String  getTwitterTimeline(){
        List<User> userInfo = [Select Id, Name, Twitter_User_Name__c From User Where Id =: UserInfo.getUserId() ];
        List<Twitter_Endpoints__mdt> endpoints = oAuth1OUtility.getEndpoints();
        String timeLine = '';
        if ( endpoints == null) {
            return null;
        } else {
            timeLine = endpoints.get(0).Timeline__c;
        }
        if(userInfo != null && userInfo.size() > 0){
            List<Twitter_Infos__mdt> tokenSecretInfo = TwitterController.twitterSecretTokenInfo(userInfo[0].Twitter_User_Name__c);
            if(tokenSecretInfo != null && tokenSecretInfo.size() > 0){
                HttpRequest httpReq = oAuth1OUtility.prepareRequest(tokenSecretInfo[0].api_endpoint__c,
                                                                    tokenSecretInfo[0].oauth_consumer_key__c,
                                                                    tokenSecretInfo[0].oauth_consumer_Secret__c,
                                                                    tokenSecretInfo[0].oauth_token__c,
                                                                    tokenSecretInfo[0].oauth_token_secret__c,
                                                                    timeLine, 'GET');
                HttpResponse httpRes = new HttpResponse();
                try{
                    httpRes = (new Http()).send(httpReq);
                    if(httpRes.getStatusCode() == 200){
                        String response = httpRes.getBody();
                        
                        return response;
                    }else{
                        String response = httpRes.getBody();
                        return response;
                    }
                }catch(Exception ex){
                    System.debug(' #### Exception Executed '+ex.getStackTraceString());
                    return ex.getStackTraceString();
                }
            }
        }
        return null;
    }
    
    @AuraEnabled
    public static void postTwitterContent(String message){
        List<User> userIn = [Select Id, Name, Twitter_User_Name__c From User Where Id =: UserInfo.getUserId() ];
        if(userIn != null && userIn.size() > 0){
            List<Twitter_Infos__mdt> tokenSecretInfo = TwitterController.twitterSecretTokenInfo(userIn[0].Twitter_User_Name__c);
            if(tokenSecretInfo != null && tokenSecretInfo.size() > 0){
                if ( message == null ) {
                    message = 'Hello There! Good Morning/Eve!! If you are able to see me I am from past - 23rd July 2019.'+
                        	  '#Integration #TwitterAPI @amit_sfdc';
                }
                String encodedMessage = EncodingUtil.URLENCODE(message,'UTF-8').replace('+', '%20');
                HttpRequest httpReq = oAuth1OUtility.prepareRequest(tokenSecretInfo[0].api_endpoint__c,
                                                                    tokenSecretInfo[0].oauth_consumer_key__c,
                                                                    tokenSecretInfo[0].oauth_consumer_Secret__c,
                                                                    tokenSecretInfo[0].oauth_token__c,
                                                                    tokenSecretInfo[0].oauth_token_secret__c,
                                                                    '/1.1/statuses/update.json?status='+encodedMessage, 'POST');
                HttpResponse httpRes = new HttpResponse();
                try{
                    httpRes = (new Http()).send(httpReq);
                    if(httpRes.getStatusCode() == 200){
                        String response = httpRes.getBody();
                    }else{
                        String response = httpRes.getBody();
                        System.debug(' Error Response ' + response);
                    }
                }catch(Exception ex){
                    System.debug(' #### Exception Executed '+ex.getStackTraceString());
                }
            }
        }
    }
}